sws/src/main/java/org/scantegrity/sws/action/DatabaseQueryActionBean.java
package org.scantegrity.sws.action;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;

import org.scantegrity.sws.action.DAOFactory;

import net.sourceforge.stripes.action.DefaultHandler;
import net.sourceforge.stripes.action.ForwardResolution;
import net.sourceforge.stripes.action.Resolution;
import net.sourceforge.stripes.validation.Validate;

public class DatabaseQueryActionBean extends RestrictedActionBean {
	String c_dbRes = "";
	@Validate(required=true) String c_queryText;
	
	public String getQuery(){ return c_queryText; }
	public void setQuery(String p_query) { c_queryText = p_query; }
	
	public String getResults()
	{
		return c_dbRes;
	}
	
	public void setResults(String p_res)
	{
		c_dbRes = p_res;
	}
	
	@DefaultHandler
	public Resolution submit()
	{
		Resolution l_userCheck = super.checkUser();
		if( l_userCheck != null ) return l_userCheck;
		
		if( c_queryText == null || c_queryText.isEmpty() )
			return new ForwardResolution("/WEB-INF/pages/databasequery.jsp");
		
		try {
			//get connection to database.
			Connection l_conn = DAOFactory.getInstance().getConnection();

			//Create SQL statement object
			Statement l_query = l_conn.createStatement();
			
			if( !l_query.execute(c_queryText) )
			{
				c_dbRes = l_query.getUpdateCount() + " row(s) successfullly updated.";
			}
			else
			{
				ResultSet l_res = l_query.getResultSet();
				c_dbRes = "<table style='width: 80%;text-align: left'><td>";
				ResultSetMetaData l_meta = l_res.getMetaData();
				for( int x = 1; x <= l_meta.getColumnCount(); x++ )
				{
					c_dbRes += "<th>" + l_meta.getColumnName(x) + "</th>";
				}
				while( l_res.next() )
				{
					c_dbRes += "<tr>";
					for( int x = 1; x <= l_meta.getColumnCount(); x++ )
					{
						c_dbRes += "<td>";
						if( l_meta.getColumnType(x) == Types.VARCHAR )
							c_dbRes += l_res.getString(x);
						else if( l_meta.getColumnType(x) == Types.INTEGER )
							c_dbRes += l_res.getInt(x);
						c_dbRes += "</td>";
					}
					c_dbRes += "</tr>";
				}
				c_dbRes += "</table>";
			}
			
		} catch (Exception e )
		{
			setResults( e.getMessage() );
		}
		finally {}
		return new ForwardResolution("/WEB-INF/pages/databasequery.jsp");
	}

}

sws/src/main/java/org/scantegrity/sws/action/GetFilesActionBean.java
package org.scantegrity.sws.action;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FilenameFilter;
import java.io.IOException;

import net.sourceforge.stripes.action.ActionBean;
import net.sourceforge.stripes.action.ActionBeanContext;
import net.sourceforge.stripes.action.ForwardResolution;
import net.sourceforge.stripes.action.Resolution;

public class GetFilesActionBean implements ActionBean {
    private static final String VIEW = "/WEB-INF/pages/getfiles.jsp";

	private String c_htmlFiles;
	private String c_error;
	
	public String getErrors()
	{
		return "<div class=\"error\">" + c_error + "</div>";
	}

	public void setErrors(String p_error)
	{
		c_error = p_error;
	}
	
	public String getHtmlFiles()
	{
		return c_htmlFiles;
	}
	
	public void setHtmlFiles(String p_newHtml)
	{
		c_htmlFiles = p_newHtml;
	}
	
    private ActionBeanContext c_ctx;
    public ActionBeanContext getContext() { 
    	return c_ctx; 
    }
    public void setContext(ActionBeanContext p_ctx) { 
    	this.c_ctx = p_ctx; 
	}
    
    public Resolution submit()
    {
    	c_htmlFiles = "";
    	c_htmlFiles += "<table width=\"80%\">";
    	c_htmlFiles += "<tr><th>File Name</th><th>Size</th></tr>";
    	
		try
		{
			File l_docsDir = new File(c_ctx.getServletContext().getRealPath("/docs/"));
			String l_docsPath = c_ctx.getServletContext().getContextPath() + "/docs/";
			if( !l_docsDir.exists() )
			{
				throw new FileNotFoundException("Could not find docs directory.");
			}
			
			File[] l_files = l_docsDir.listFiles(new HiddenFileFilter());
			
			for(File l_newFile : l_files)
			{
				c_htmlFiles += "<tr>";
				c_htmlFiles += "<td><a href=" + l_docsPath + l_newFile.getName() + ">";
				c_htmlFiles += l_newFile.getName() + "</a></td>";
				c_htmlFiles += "<td>" + l_newFile.length() + "</td></tr>";
			}
			c_htmlFiles += "</table>";
		}
		catch(IOException e)
		{
			c_error += e.getMessage() + "\n";
		}
    	
    	return new ForwardResolution(VIEW);
    }
	
    class HiddenFileFilter implements FilenameFilter
    {

		public boolean accept(File dir, String name) {
			return name.charAt(0) != '.';
		}
    	
    }
    
}

sws/src/main/java/org/scantegrity/sws/action/StaticActionBean.java
package org.scantegrity.sws.action;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.util.Enumeration;
import java.util.Scanner;

import net.sourceforge.stripes.action.DefaultHandler;
import net.sourceforge.stripes.action.Resolution;

import javax.servlet.http.HttpSession;
import org.apache.commons.lang.StringEscapeUtils;

public class StaticActionBean extends DefaultActionBean {
	
	protected String c_htmlPath;
	
	public StaticActionBean()
	{
		super();
		c_htmlPath = "";
	}
	
	public StaticActionBean(String p_htmlPath)
	{
		c_htmlPath = p_htmlPath;
	}
	
	public String getHtml()
	{
		String l_html = "";
		try {
			String l_htmlPath = c_ctx.getServletContext().getRealPath("/WEB-INF/pages/");
			if( l_htmlPath.charAt(l_htmlPath.length() - 1) != File.separatorChar )
				l_htmlPath = l_htmlPath + File.separator;
			
			l_htmlPath = l_htmlPath + c_htmlPath;
			Scanner l_reader = new Scanner(new BufferedReader(new InputStreamReader(new FileInputStream(l_htmlPath))));
			l_html = l_reader.useDelimiter("\\Z").next(); 
			l_reader.close();
			l_html =  l_html.replace("${pageContext.request.contextPath}", getContext().getServletContext().getContextPath());
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			StringWriter l_writer = new StringWriter();
			e.printStackTrace(new PrintWriter(l_writer));
			return l_writer.toString();
		}
		HttpSession c_sess = getContext().getRequest().getSession(true);
		if( c_sess.getAttribute("username") != null )
		{
			l_html = StringEscapeUtils.escapeHtml(l_html);
			l_html = "<form method='post'><textarea name='editor1'>" + l_html + "</textarea><script type=\"text/javascript\">CKEDITOR.replace( 'editor1' );</script><input type=\"submit\"></form>";
		}
		return l_html;
	}
	
	@Override
	public Resolution view()
	{
		String[] l_values = c_ctx.getRequest().getParameterValues("editor1");
		if( l_values != null && l_values.length > 0 && l_values[0] != null && c_ctx.getRequest().getSession(true).getAttribute("username") != null )
			setHtml(l_values[0]);
		return super.view();
	}
	
	public void setHtml(String p_html)
	{
		try{
			String l_htmlPath = c_ctx.getServletContext().getRealPath("/WEB-INF/pages/") + c_htmlPath;
			BufferedWriter l_writer = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(l_htmlPath)));
			l_writer.write(p_html);
			l_writer.close();
		}
		catch(FileNotFoundException e)
		{
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

}

sws/src/main/java/org/scantegrity/sws/action/UserAddActionBean.java
package org.scantegrity.sws.action;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.NoSuchElementException;

import org.scantegrity.sws.action.DAOFactory;

import net.sourceforge.stripes.action.ActionBeanContext;
import net.sourceforge.stripes.action.DefaultHandler;
import net.sourceforge.stripes.action.ForwardResolution;
import net.sourceforge.stripes.action.HandlesEvent;
import net.sourceforge.stripes.action.Resolution;

public class UserAddActionBean extends RestrictedActionBean {
	private static final String VIEW = "/WEB-INF/pages/useradd.jsp";
	
	private List<String> c_allUsers;
	private String c_error = "";
	private String c_target;
	private String c_newUser;
	private String c_pass;
	
	public String getUsername() { return c_newUser; }
	public void setUsername(String p_user) { c_newUser = p_user; }
	public String getPassword() { return c_pass; }
	public void setPassword(String p_pass) { c_pass = p_pass; }
	
	public String getTarget()
	{
		return c_target;
	}
	public void setTarget(String p_target)
	{
		c_target = p_target;
	}
	
	public List<String> getAllUsers()
	{
		return c_allUsers;
	}
	
	public void setAllUsers(List<String> p_users)
	{
		c_allUsers = p_users;
	}
	
	public String getErrors()
	{
		return "<div class=\"error\">" + c_error + "</div>";
	}

	public void setErrors(String p_error)
	{
		c_error = p_error;
	}
	
	@HandlesEvent(value="addUser")
	public Resolution addUser()
	{
		try
		{
			UserManage.addUser(c_newUser, c_pass);
		} catch (SQLException e) {
			c_error = "Could not execute SQL: " + e.getMessage();
		} catch (InstantiationException e) {
			c_error = "Could not load derby driver: instantiation exception";
		} catch (IllegalAccessException e) {
			c_error = "Could not load derby driver: illegal access exception";
		} catch (ClassNotFoundException e) {
			c_error = "Could not load derby driver: class not found exception";
		} catch (NoSuchElementException e)
		{
			c_error = "Could not locate ballot with given serial. Please try again.";
		}
		
		return submit();
	}
	
	@HandlesEvent(value="deleteUser")
	public Resolution deleteUser()
	{
		try
		{
			UserManage.removeUser(c_target);
		} catch (SQLException e) {
			c_error = "Could not execute SQL: " + e.getMessage();
		} catch (InstantiationException e) {
			c_error = "Could not load derby driver: instantiation exception";
		} catch (IllegalAccessException e) {
			c_error = "Could not load derby driver: illegal access exception";
		} catch (ClassNotFoundException e) {
			c_error = "Could not load derby driver: class not found exception";
		} catch (NoSuchElementException e)
		{
			c_error = "Could not locate ballot with given serial. Please try again.";
		}
		
		return submit();
	}
	
	@DefaultHandler
	public Resolution submit()
	{
		Resolution l_userCheck = super.checkUser();
		if( l_userCheck != null ) return l_userCheck;
		
		
		ArrayList<String> l_users = new ArrayList<String>();
		try
		{
			//Load derby database driver
			Class.forName("org.apache.derby.jdbc.ClientDriver").newInstance();
			//Create connection to database.  Create database if it doesn't exist.
			Connection l_conn = DAOFactory.getInstance().getConnection();
	
			//Create SQL statement object
			PreparedStatement l_query = l_conn.prepareStatement("SELECT username FROM users");
			
			ResultSet l_res = l_query.executeQuery();
			while( l_res.next() )
			{
				l_users.add(l_res.getString("username"));
			}
		} catch (SQLException e) {
			c_error = "Could not execute SQL: " + e.getMessage();
		} catch (InstantiationException e) {
			c_error = "Could not load derby driver: instantiation exception";
		} catch (IllegalAccessException e) {
			c_error = "Could not load derby driver: illegal access exception";
		} catch (ClassNotFoundException e) {
			c_error = "Could not load derby driver: class not found exception";
		} catch (NoSuchElementException e)
		{
			c_error = "Could not locate ballot with given serial. Please try again.";
		}
		c_allUsers = l_users;
		
		return new ForwardResolution(VIEW);
	}
	
	
}

sws/src/main/webapp/WEB-INF/pages/admin.jsp
<%@ taglib prefix="stripes" uri="http://stripes.sourceforge.net/stripes.tld" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<stripes:layout-render name="/WEB-INF/layout/default.jsp">
    <stripes:layout-component name="contents">
    <h1>Admin Panel</h1>
    <p>
    	<a href="fileupload">Upload files</a><br/><br/>
    	<a href="useradd">Manage users</a>
    	<stripes:form beanclass="org.scantegrity.sws.action.AdminActionBean">
    		<stripes:submit name="deleteDatabase" value="Delete Database" />
    	</stripes:form>
    	<stripes:form beanclass="org.scantegrity.sws.action.AdminActionBean">
    		<stripes:submit name="logout" value="Logout" />
    	</stripes:form>
    </p>
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    
    </stripes:layout-component>
</stripes:layout-render>

sws/src/main/webapp/WEB-INF/pages/checkcodes.jsp
<%@taglib prefix="stripes" uri="http://stripes.sourceforge.net/stripes.tld"%>

<stripes:layout-render name="/WEB-INF/layout/default.jsp">
    <stripes:layout-component name="contents">
<h1>Check Codes</h1>

<p>Please input your online verification number below.  Any questions or concerns should be directed <a href="contact">here</a>.  </p>
<stripes:form beanclass="org.scantegrity.sws.action.CheckCodesActionBean">
<p>
	<label for="name">Serial:</label>
	<input type="text" id="serial" name="serial" value="${actionBean.serial}" />
	<stripes:submit name="submit" value="Submit" />
	<br /><br />
	
	<br />
	
	<stripes:errors/>
	
	${actionBean.result}
	<br/><br/>
	${actionBean.errors}
	<br/>

	<p>Please also help us by taking a <a href="https://www.surveymonkey.com/s/HLFZXRS">short survey here</a> about your voting experience.</p>
	
	
</p>
</stripes:form> 

    </stripes:layout-component>
</stripes:layout-render>

sws/src/main/webapp/WEB-INF/pages/contact-success.jsp
<%@ taglib prefix="stripes" uri="http://stripes.sourceforge.net/stripes.tld" %>

<stripes:layout-render name="/WEB-INF/layout/default.jsp">
    <stripes:layout-component name="contents">
    <h1>Thank You!</h1>
    
    <p>Your message has been sent successfully!</p>
    
    <p>We will respond to your message as soon as possible. If you have not 
    received a response within 2 days, or are unhappy with the response 
    received, please contact the <a href="http://takomaparkmd.gov/clerk">City 
    Clerk</a>.</p>
    
    <br />
    <br />
    <br />
    <br />
    <br />
    </stripes:layout-component>
</stripes:layout-render>    
    

sws/src/main/webapp/WEB-INF/pages/contact.jsp
<%@ taglib prefix="stripes" uri="http://stripes.sourceforge.net/stripes.tld" %>

<stripes:layout-render name="/WEB-INF/layout/default.jsp">
    <stripes:layout-component name="html_head">
        <link rel="stylesheet" type="text/css" href="${pageContext['request'].contextPath}/styles/forms.css" />
    </stripes:layout-component>
    <stripes:layout-component name="contents">
    <h1>Contact Us</h1>

		<p>Please fill out the following form, and we will get back to you
		as soon as possible.</p>

		<stripes:form beanclass="org.scantegrity.sws.action.ContactActionBean" class="stylishform">
		<fieldset><legend>Contact Form</legend>
            <span style="color:red;"><stripes:errors/></span>		
		<ol>
			<li><label for="name">Name</label> <stripes:text id="name"
				name="name" style="width: 50%;" /></li>

			<li><label for="email">E-mail Address</label> 
			     <stripes:text id="email" name="email"
				    style="width: 50%;" /></li>

			<li><label for="subject">Subject</label> <stripes:text
				id="subject" name="subject" style="width: 55%;" /></li>

			<li><label for="msg">Message</label><br />

			<stripes:textarea id="msg" name="msg" cols="65" rows="20"></stripes:textarea>

			</li>
			<li>${actionBean.captchaHTML}</li>
			<li><stripes:submit name="submit" value="Send Message" /></li>
		</ol>
		</fieldset> 
		</stripes:form>


	<br />
	<br />
	</stripes:layout-component>
</stripes:layout-render>

sws/src/main/webapp/WEB-INF/pages/databasequery.jsp
<%@taglib prefix="stripes" uri="http://stripes.sourceforge.net/stripes.tld"%>

<stripes:layout-render name="/WEB-INF/layout/default.jsp">
    <stripes:layout-component name="contents">
<h1>Database Query</h1>

<p>Input database query text below</p>
<stripes:form beanclass="org.scantegrity.sws.action.DatabaseQueryActionBean">
<p>
	<label for="name">Query:</label>
	<input type="text" id="query" name="query" value="${actionBean.query}" />
	<stripes:submit name="submit" value="Submit" />
	<br /><br />
	
	<br />
	
	<stripes:errors/>
	${actionBean.results}
	<br/>
	
</p>
</stripes:form> 

    </stripes:layout-component>
</stripes:layout-render>

sws/src/main/webapp/WEB-INF/pages/faq.jsp
<%@ taglib prefix="stripes" uri="http://stripes.sourceforge.net/stripes.tld" %>
<stripes:layout-render name="/WEB-INF/layout/default.jsp">
    <stripes:layout-component name="contents">
    ${actionBean.html }
   </stripes:layout-component>
</stripes:layout-render>

sws/src/main/webapp/WEB-INF/pages/fileupload.jsp
<%@taglib prefix="stripes" uri="http://stripes.sourceforge.net/stripes.tld"%>
<stripes:layout-render name="/WEB-INF/layout/default.jsp">
    <stripes:layout-component name="contents">


<h1>File Upload</h1>

<stripes:form beanclass="org.scantegrity.sws.action.FileuploadActionBean">
<div>
	<stripes:file name="file" /></br>
	<label for="name">Style ID (for codes only):</label>
	<input type="text" id="styleId" name="styleId" value="${actionBean.styleId}" />
	<stripes:submit name="submit" value="Upload" />
	<br /><br />
	
	<br />
	
	<stripes:errors/>
	
	<br/><br/>
	${actionBean.result}
	<br/><br/>
	${actionBean.errors}
	  </div>
</stripes:form> 

    </stripes:layout-component>
</stripes:layout-render>

sws/src/main/webapp/WEB-INF/pages/getfiles.jsp
<%@taglib prefix="stripes" uri="http://stripes.sourceforge.net/stripes.tld"%>

<stripes:layout-render name="/WEB-INF/layout/default.jsp">
    <stripes:layout-component name="contents">
    
    <h1>Election Files</h1>
    
    <stripes:form beanclass="org.scantegrity.sws.action.GetFilesActionBean">
    
    
    	${actionBean.htmlFiles}
    	
    	<br/><br/>
        <br/><br/>
        <br/><br/>
        <br/><br/>
        <br/><br/>
    
    </stripes:form>
    
        </stripes:layout-component>
</stripes:layout-render>

sws/src/main/webapp/WEB-INF/pages/hello.jsp
<%@ taglib prefix="stripes" uri="http://stripes.sourceforge.net/stripes.tld" %>
<stripes:layout-render name="/WEB-INF/layout/default.jsp">
    <stripes:layout-component name="contents">
   <h1>Welcome!</h1>
 
    </stripes:layout-component>
</stripes:layout-render>

sws/src/main/webapp/WEB-INF/pages/i18n.jsp
<%@taglib prefix="s" uri="http://stripes.sourceforge.net/stripes.tld"%>


<h1>Scantegrity Internationalization Test</h1>
The selected name and language, or your Browser's name and default language, 
should appear in the text below:

<h3>
			<fmt:message key="greeting">
				<fmt:param>${actionBean.name}</fmt:param>
			</fmt:message>
			<fmt:message key="return"/>
</h3>

<s:form beanclass="action.i18nActionBean">
<fieldset>
    <legend>Change Locale Settings</legend>
	<ol>
	    <li>
	        <label for="name">Name</label>
	        <input type="text" id="name" name="name" value="${sessionScope.name}" /><br />
	    </li>
	    <li>
	        <label for="locale">Locale</label>
	        <s:select id="locale" name="locale">
				 <s:option value="en">English (en)</s:option>
				 <s:option value="fr">French (fr)</s:option>
	    		 <s:option value="de">German (de)</s:option>
				 <s:option value="es">Spanish (es)</s:option>
	        </s:select>
	    </li>
	</ol>
	<br />
	<s:submit name="submit" value="Change Locale" />
</fieldset>
</s:form>

<br /><br />
<h3>Other Info</h3>

<p>Your browser's detected locale was: ${header['Accept-Language']}</p>
<p>Your browser's detected name was: ${header['User-Agent']}
<p>The current set locale is: ${actionBean.locale}
<br /><br />

sws/src/main/webapp/WEB-INF/pages/index.jsp
<%@ taglib prefix="stripes" uri="http://stripes.sourceforge.net/stripes.tld" %>
<stripes:layout-render name="/WEB-INF/layout/default.jsp">
    <stripes:layout-component name="contents">
    ${actionBean.html}
    </stripes:layout-component>
</stripes:layout-render>

sws/src/main/webapp/WEB-INF/pages/login.jsp
<%@taglib prefix="stripes" uri="http://stripes.sourceforge.net/stripes.tld"%>

<stripes:layout-render name="/WEB-INF/layout/default.jsp">
    <stripes:layout-component name="contents">
<h1>Login</h1>

<p>The page you were trying to access is restricted, please enter your user name and password below:</p>
<stripes:form beanclass="org.scantegrity.sws.action.LoginActionBean">

	<label for="username">User Name:</label>
	<input type="text" id="username" name="username" value="${actionBean.username}" /> <br/>
	<label for="password">Password:</label>
	<input type="password" id="password" name="password" /> <br/>
	<stripes:submit name="submit" value="Submit" />
	<br /><br />
	
	<br />
	
	<stripes:errors/>
	
	<br/><br/>
	${actionBean.errors}
	
</stripes:form> 

    </stripes:layout-component>
</stripes:layout-render>

sws/src/main/webapp/WEB-INF/pages/results.jsp
<%@ taglib prefix="stripes" uri="http://stripes.sourceforge.net/stripes.tld" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<stripes:layout-render name="/WEB-INF/layout/default.jsp">
    <stripes:layout-component name="contents">
    <h1>Results</h1>
    <stripes:form beanclass="org.scantegrity.sws.action.ResultsActionBean">
    <p><i>What is shown below are unofficial results. Please go to the 
    <a href="http://www.takomaparkmd.gov/clerk/election/2009/results/index.html">
    Official Takoma Park Results page</a>. Note that the handcount did count 
    ballots that were not recognized by the scanner, and this page only shows 
    the scanner tallies. Takoma Park counts any ballot with discernable voter 
    preference on it.</i></p>
    <!--<c:if test="${actionBean.results != \"\" }"><p><i>For results with 
    write-in candidates, click <a href="results?writein=n">here.</a></i></p>
    </c:if>//-->
    <p><c:if test="${empty actionBean.results}">Please click 
    <a href="results?writein=y">here</a> for results.
    </c:if>${actionBean.results }</p>
    </stripes:form>
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    
    </stripes:layout-component>
</stripes:layout-render>

sws/src/main/webapp/WEB-INF/pages/useradd.jsp
<%@taglib prefix="stripes" uri="http://stripes.sourceforge.net/stripes.tld"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<stripes:layout-render name="/WEB-INF/layout/default.jsp">
    <stripes:layout-component name="contents">
<h1>User Management</h1>

<p>Enter user name and password below to add new user:</p>
<stripes:form beanclass="org.scantegrity.sws.action.UserAddActionBean">

	<label for="username">User Name:</label>
	<input type="text" id="username" name="username" value="${actionBean.username}" /> <br/>
	<label for="password">Password:</label>
	<input type="password" id="password" name="password" /> <br/>
	<stripes:submit name="addUser" value="Submit" />
	<br />
	
	<br />
	
	<stripes:errors/>
	${actionBean.errors}
	
</stripes:form> 

<stripes:form beanclass="org.scantegrity.sws.action.LoginActionBean">
<table style="width: 80%">
<tr><th>User Name</th><th></th></tr>
	<c:forEach items="${actionBean.allUsers}" var="user">
		<tr>
			<td>${user}</td>
			<td>
				<stripes:link href="/useradd" event="deleteUser">
					Delete 
					<stripes:param name="target" value="${user}" />
				</stripes:link>
			</td>
		</tr>
	</c:forEach>
</table>
</stripes:form>

    </stripes:layout-component>
</stripes:layout-render>